name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24', 'stable']
    name: Build with Go ${{ matrix.go-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
        
      - name: Build
        run: go build -v ./cmd/aliaz/...
      
      - name: Test
        run: go test -v ./cmd/aliaz/...

      - name: Gofmt
        # Run gofmt, print the output and exit with status code 1 if it isn't empty.
        run: |
          OUTPUT=$(gofmt -d ./)
          echo "$OUTPUT"
          test -z "$OUTPUT"
      
