name: Go Cross-Platform Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build, Package, and Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build binary
        run: |
          mkdir -p dist
          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then EXT=".exe"; fi

          BIN_NAME="aliaz"
          ARCHIVE_NAME="${BIN_NAME}-${{ matrix.goos }}-${{ matrix.goarch }}"

          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ${BIN_NAME}$EXT ./cmd/aliaz/...

          if [ "${{ matrix.goos }}" = "windows" ]; then
            zip -j "dist/${ARCHIVE_NAME}.zip" "${BIN_NAME}$EXT"
          else
            tar -czvf "dist/${ARCHIVE_NAME}.tar.gz" "${BIN_NAME}$EXT"
          fi

          rm "${BIN_NAME}$EXT"

      - name: Generate checksums
        run: |
          cd dist
          shasum -a 256 * > SHA256SUMS.txt

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
